### ISSUE TITLE
Blank

### ISSUE THREAD

**Issue by hendrylouis** [Bonfida/swap-ui#2]
why after install yarn and start yarn dev, web app blank not show anything..

**Comment by hendrylouis** [comment]
need .env.local and .env.production files for running the program ?|

then filled with this script

VITE_RPC= Your RPC URL
VITE_FEES= The address used to collect fees
VITE_FEES_BPS= The fees you want to charge on transaction
VITE_GEN_GO_TOKEN= The URL to fetch the auth token (might not be applicable)
GENERATE_SOURCEMAP=false

**Comment by hendrylouis** [comment]
![console](https://user-images.githubusercontent.com/91595823/164645175-87e85df3-5cb1-451c-9bd0-ab392a25e05c.png)

**Comment by dr497** [comment]
You need at least the `.env. local` to run the project locally

**Comment by hendrylouis** [comment]
can i get example for .env. local ???

**Comment by hendrylouis** [comment]
thanks budy i forgot that's
